// Static mock data for ET Navigator

export const events = [
  {
    id: "event-1",
    title: "ET Startup Awards 2026",
    description: "Celebrating India's most innovative startups and entrepreneurs reshaping the business landscape.",
    category: "events",
    tags: ["startup", "innovation", "awards"],
    audience: ["Business Owner", "Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    link: "https://economictimes.indiatimes.com/small-biz/startups",
    date: "Apr 15, 2026",
    location: "Mumbai",
    eventType: "Awards"
  },
  {
    id: "event-2",
    title: "Global Business Summit India",
    description: "Industry leaders gather to discuss the future of global commerce and India's role in it.",
    category: "events",
    tags: ["business", "leadership", "global"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&q=80",
    link: "https://economictimes.indiatimes.com/et-events",
    date: "May 8, 2026",
    location: "New Delhi",
    eventType: "Summit"
  },
  {
    id: "event-3",
    title: "Women in Leadership Forum",
    description: "Empowering women leaders across industries with insights from top executives.",
    category: "events",
    tags: ["leadership", "diversity", "women"],
    audience: ["Working Professional", "Student"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=800&q=80",
    link: "https://economictimes.indiatimes.com/et-events",
    date: "Apr 22, 2026",
    location: "Bengaluru",
    eventType: "Forum"
  },
  {
    id: "event-4",
    title: "FinTech Festival India 2026",
    description: "Exploring innovations in financial technology with demos, panels, and networking.",
    category: "events",
    tags: ["fintech", "technology", "finance"],
    audience: ["Working Professional", "Business Owner", "Student"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech",
    date: "Jun 12, 2026",
    location: "Mumbai",
    eventType: "Festival"
  },
  {
    id: "event-5",
    title: "ET Real Estate Summit",
    description: "Deep dive into India's booming real estate market with expert analysis.",
    category: "events",
    tags: ["real estate", "investment", "property"],
    audience: ["Business Owner", "Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/real-estate",
    date: "May 20, 2026",
    location: "Gurugram",
    eventType: "Summit"
  },
  {
    id: "event-6",
    title: "AI & Future of Work Conference",
    description: "How AI is reshaping industries, employment, and career opportunities.",
    category: "events",
    tags: ["AI", "technology", "careers"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/artificial-intelligence",
    date: "Jul 5, 2026",
    location: "Online",
    eventType: "Conference"
  },
  {
    id: "event-7",
    title: "Healthcare Innovation Summit",
    description: "Exploring breakthrough technologies transforming healthcare delivery.",
    category: "events",
    tags: ["healthcare", "innovation", "medtech"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/industry/healthcare-biotech",
    date: "Aug 18, 2026",
    location: "Hyderabad",
    eventType: "Summit"
  },
  {
    id: "event-8",
    title: "Sustainable Business Forum",
    description: "Leaders discuss ESG strategies and building climate-resilient businesses.",
    category: "events",
    tags: ["sustainability", "ESG", "climate"],
    audience: ["Business Owner", "Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=800&q=80",
    link: "https://economictimes.indiatimes.com/small-biz/sustainability",
    date: "Sep 10, 2026",
    location: "Mumbai",
    eventType: "Forum"
  },
  {
    id: "event-9",
    title: "Digital Marketing Masterclass Live",
    description: "Interactive workshop on growth hacking and performance marketing.",
    category: "events",
    tags: ["marketing", "digital", "growth"],
    audience: ["Student", "Working Professional", "Business Owner"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    date: "Apr 28, 2026",
    location: "Online",
    eventType: "Workshop"
  },
  {
    id: "event-10",
    title: "Investor Connect 2026",
    description: "Networking event connecting startups with angel investors and VCs.",
    category: "events",
    tags: ["investing", "startup", "networking"],
    audience: ["Business Owner", "Working Professional"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1553028826-f4804a6dba3b?w=800&q=80",
    link: "https://economictimes.indiatimes.com/small-biz/startups",
    date: "Jun 25, 2026",
    location: "Bengaluru",
    eventType: "Networking"
  },
  {
    id: "event-11",
    title: "EdTech India Conference",
    description: "Future of education: AI tutors and skill development ecosystems.",
    category: "events",
    tags: ["education", "technology", "edtech"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80",
    link: "https://economictimes.indiatimes.com/industry/services/education",
    date: "Jul 22, 2026",
    location: "Pune",
    eventType: "Conference"
  },
  {
    id: "event-12",
    title: "Manufacturing Excellence Summit",
    description: "Industry 4.0 and the future of manufacturing in India.",
    category: "events",
    tags: ["manufacturing", "industry", "automation"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&q=80",
    link: "https://economictimes.indiatimes.com/industry/indl-goods/svs/engineering",
    date: "Aug 5, 2026",
    location: "Chennai",
    eventType: "Summit"
  }
];

export const masterclasses = [
  {
    id: "masterclass-1",
    title: "Stock Market Fundamentals",
    description: "Learn the basics of investing in Indian stock markets with hands-on exercises.",
    category: "masterclasses",
    tags: ["investing", "stocks", "trading"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    duration: "4 weeks",
    instructor: "Rajesh Sharma",
    level: "Beginner"
  },
  {
    id: "masterclass-2",
    title: "Personal Finance Mastery",
    description: "Master budgeting, saving, and wealth building strategies.",
    category: "masterclasses",
    tags: ["finance", "budgeting", "wealth"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    duration: "3 weeks",
    instructor: "Priya Mehta",
    level: "Beginner"
  },
  {
    id: "masterclass-3",
    title: "Leadership Excellence Program",
    description: "Develop advanced leadership skills with real-world case studies.",
    category: "masterclasses",
    tags: ["leadership", "management", "career"],
    audience: ["Working Professional"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    duration: "8 weeks",
    instructor: "Dr. Anil Kumar",
    level: "Advanced"
  },
  {
    id: "masterclass-4",
    title: "Cryptocurrency & Blockchain",
    description: "Understanding blockchain technology and decentralized finance.",
    category: "masterclasses",
    tags: ["crypto", "blockchain", "fintech"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    duration: "3 weeks",
    instructor: "Vikram Singh",
    level: "Beginner"
  },
  {
    id: "masterclass-5",
    title: "Business Strategy Essentials",
    description: "Strategic thinking frameworks for entrepreneurs and managers.",
    category: "masterclasses",
    tags: ["strategy", "business", "management"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    duration: "6 weeks",
    instructor: "Sunita Rao",
    level: "Intermediate"
  },
  {
    id: "masterclass-6",
    title: "Tax Planning & Optimization",
    description: "Optimize your taxes legally with expert strategies.",
    category: "masterclasses",
    tags: ["tax", "finance", "planning"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    duration: "4 weeks",
    instructor: "CA Deepak Jain",
    level: "Intermediate"
  },
  {
    id: "masterclass-7",
    title: "Data Analytics for Business",
    description: "Leverage data for better decisions using modern analytics tools.",
    category: "masterclasses",
    tags: ["data", "analytics", "technology"],
    audience: ["Working Professional", "Student"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    duration: "5 weeks",
    instructor: "Neha Gupta",
    level: "Intermediate"
  },
  {
    id: "masterclass-8",
    title: "Digital Marketing Certification",
    description: "Complete guide to SEO, SEM, and performance advertising.",
    category: "masterclasses",
    tags: ["marketing", "digital", "social media"],
    audience: ["Student", "Working Professional", "Business Owner"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1432888622747-4eb9a8f2c6b8?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    duration: "6 weeks",
    instructor: "Amit Verma",
    level: "Beginner"
  },
  {
    id: "masterclass-9",
    title: "Financial Modeling & Valuation",
    description: "Build professional financial models and learn valuation techniques.",
    category: "masterclasses",
    tags: ["finance", "modeling", "valuation"],
    audience: ["Working Professional", "Student"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    duration: "8 weeks",
    instructor: "Sanjay Kapoor",
    level: "Advanced"
  },
  {
    id: "masterclass-10",
    title: "Product Management Bootcamp",
    description: "Master the complete product lifecycle management process.",
    category: "masterclasses",
    tags: ["product", "management", "tech"],
    audience: ["Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1512758017271-d7b84c2113f1?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    duration: "6 weeks",
    instructor: "Ritu Sharma",
    level: "Intermediate"
  },
  {
    id: "masterclass-11",
    title: "Entrepreneurship 101",
    description: "Start your entrepreneurial journey with proven frameworks.",
    category: "masterclasses",
    tags: ["startup", "entrepreneurship", "business"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    duration: "4 weeks",
    instructor: "Karan Bajaj",
    level: "Beginner"
  },
  {
    id: "masterclass-12",
    title: "AI & Machine Learning for Managers",
    description: "Non-technical guide to implementing AI in your organization.",
    category: "masterclasses",
    tags: ["AI", "technology", "management"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
    link: "https://masterclass.economictimes.indiatimes.com/",
    duration: "5 weeks",
    instructor: "Dr. Meera Patel",
    level: "Intermediate"
  }
];

export const markets = [
  {
    id: "market-1",
    title: "Sensex Hits All-Time High Above 85,000",
    description: "Indian markets rally as FIIs increase allocations to emerging markets.",
    category: "markets",
    tags: ["sensex", "stocks", "FII"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets/stocks",
    price: "85,247",
    change: "+1.8%",
    trend: "up",
    type: "Index"
  },
  {
    id: "market-2",
    title: "Nifty IT Index Surges on Q4 Results",
    description: "Tech stocks lead gains amid better-than-expected quarterly earnings.",
    category: "markets",
    tags: ["nifty", "IT", "stocks"],
    audience: ["Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets/stocks/news",
    price: "38,920",
    change: "+2.4%",
    trend: "up",
    type: "Index"
  },
  {
    id: "market-3",
    title: "Gold Prices Rise on Safe-Haven Demand",
    description: "Precious metals surge as global uncertainties drive investors.",
    category: "markets",
    tags: ["gold", "commodities", "investment"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1610375461246-83df859d849d?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets/commodities",
    price: "72,450",
    change: "+0.9%",
    trend: "up",
    type: "Commodity"
  },
  {
    id: "market-4",
    title: "Rupee Strengthens Against Dollar",
    description: "RBI intervention and strong FII inflows support the domestic currency.",
    category: "markets",
    tags: ["forex", "rupee", "RBI"],
    audience: ["Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets/forex",
    price: "82.35",
    change: "+0.3%",
    trend: "up",
    type: "Forex"
  },
  {
    id: "market-5",
    title: "Bitcoin Crosses $100K",
    description: "Cryptocurrency markets surge as institutions increase holdings.",
    category: "markets",
    tags: ["crypto", "bitcoin", "investment"],
    audience: ["Student", "Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1518544801976-3e159e50e5bb?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets/cryptocurrency",
    price: "102,340",
    change: "+5.2%",
    trend: "up",
    type: "Crypto"
  },
  {
    id: "market-6",
    title: "Midcap Stocks Outperform Large Caps",
    description: "Midcap index gains 4% as retail investors hunt for growth.",
    category: "markets",
    tags: ["midcap", "stocks", "growth"],
    audience: ["Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets/stocks",
    price: "48,670",
    change: "+3.1%",
    trend: "up",
    type: "Index"
  },
  {
    id: "market-7",
    title: "Banking Stocks Rally on Credit Growth",
    description: "Financial sector leads gains as loan data exceeds expectations.",
    category: "markets",
    tags: ["banking", "stocks", "finance"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets/stocks/news",
    price: "52,180",
    change: "+1.6%",
    trend: "up",
    type: "Sector"
  },
  {
    id: "market-8",
    title: "Crude Oil Volatile on OPEC Decisions",
    description: "Energy markets remain choppy as OPEC+ debates production cuts.",
    category: "markets",
    tags: ["oil", "commodities", "energy"],
    audience: ["Working Professional"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1545243424-0ce743321e11?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets/commodities",
    price: "78.45",
    change: "-1.2%",
    trend: "down",
    type: "Commodity"
  },
  {
    id: "market-9",
    title: "IPO Market: 5 Major Listings This Month",
    description: "Tech and consumer companies line up for public offerings.",
    category: "markets",
    tags: ["IPO", "stocks", "investing"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets/ipo",
    price: "12,500 Cr",
    change: "New",
    trend: "up",
    type: "IPO"
  },
  {
    id: "market-10",
    title: "Pharma Shows Resilience Amid Volatility",
    description: "Healthcare stocks remain defensive play in uncertain conditions.",
    category: "markets",
    tags: ["pharma", "healthcare", "stocks"],
    audience: ["Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets/stocks",
    price: "18,340",
    change: "+0.4%",
    trend: "up",
    type: "Sector"
  },
  {
    id: "market-11",
    title: "Bond Yields Fall as RBI Signals Pause",
    description: "Fixed income markets rally on stable monetary policy expectations.",
    category: "markets",
    tags: ["bonds", "RBI", "fixed income"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets/bonds",
    price: "7.12%",
    change: "-0.05%",
    trend: "down",
    type: "Bonds"
  },
  {
    id: "market-12",
    title: "Auto Stocks Gain on Strong Sales Data",
    description: "Automobile sector rallies as manufacturers report double-digit growth.",
    category: "markets",
    tags: ["auto", "stocks", "sales"],
    audience: ["Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
    link: "https://economictimes.indiatimes.com/industry/auto",
    price: "22,890",
    change: "+2.8%",
    trend: "up",
    type: "Sector"
  }
];

export const prime = [
  {
    id: "prime-1",
    title: "The Rise of India's EV Industry",
    description: "Deep dive into the electric vehicle revolution in India and the companies leading the charge.",
    category: "prime",
    tags: ["EV", "auto", "technology"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80",
    link: "https://economictimes.indiatimes.com/prime",
    readTime: "8 min",
    contentType: "Deep Dive"
  },
  {
    id: "prime-2",
    title: "Budget 2026: Complete Analysis",
    description: "Expert analysis of key budget announcements and what they mean for your investments.",
    category: "prime",
    tags: ["budget", "policy", "economy"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/prime",
    readTime: "12 min",
    contentType: "Analysis"
  },
  {
    id: "prime-3",
    title: "Inside India's Unicorn Factory",
    description: "How startups are building billion-dollar companies and what makes them successful.",
    category: "prime",
    tags: ["startup", "unicorn", "entrepreneurship"],
    audience: ["Student", "Working Professional", "Business Owner"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80",
    link: "https://economictimes.indiatimes.com/prime",
    readTime: "6 min",
    contentType: "Feature"
  },
  {
    id: "prime-4",
    title: "The Future of Hybrid Work",
    description: "How companies are adapting to hybrid models and what it means for employees.",
    category: "prime",
    tags: ["work", "careers", "HR"],
    audience: ["Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80",
    link: "https://economictimes.indiatimes.com/prime",
    readTime: "5 min",
    contentType: "Opinion"
  },
  {
    id: "prime-5",
    title: "Banking Sector Outlook 2026",
    description: "NPAs, credit growth, and digital transformation - what to expect this fiscal.",
    category: "prime",
    tags: ["banking", "finance", "analysis"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/prime",
    readTime: "10 min",
    contentType: "Analysis"
  },
  {
    id: "prime-6",
    title: "Green Energy: Investment Opportunities",
    description: "Exploring lucrative opportunities in India's renewable energy sector.",
    category: "prime",
    tags: ["energy", "sustainability", "investing"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80",
    link: "https://economictimes.indiatimes.com/prime",
    readTime: "7 min",
    contentType: "Analysis"
  },
  {
    id: "prime-7",
    title: "India's Semiconductor Ambitions",
    description: "The billion-dollar push to make India a global chip manufacturing hub.",
    category: "prime",
    tags: ["semiconductor", "technology", "manufacturing"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    link: "https://economictimes.indiatimes.com/prime",
    readTime: "9 min",
    contentType: "Deep Dive"
  },
  {
    id: "prime-8",
    title: "AI Revolution in Indian Enterprises",
    description: "How India Inc is leveraging AI to transform operations and drive growth.",
    category: "prime",
    tags: ["AI", "technology", "enterprise"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
    link: "https://economictimes.indiatimes.com/prime",
    readTime: "6 min",
    contentType: "Feature"
  },
  {
    id: "prime-9",
    title: "Real Estate: Tier 2 Cities Boom",
    description: "Why smart investors are looking beyond metros for property investments.",
    category: "prime",
    tags: ["real estate", "investment", "property"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    link: "https://economictimes.indiatimes.com/prime",
    readTime: "7 min",
    contentType: "Analysis"
  },
  {
    id: "prime-10",
    title: "Rise of Indian SaaS Companies",
    description: "How homegrown software companies are conquering global markets.",
    category: "prime",
    tags: ["SaaS", "technology", "startup"],
    audience: ["Working Professional", "Business Owner", "Student"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/prime",
    readTime: "8 min",
    contentType: "Feature"
  },
  {
    id: "prime-11",
    title: "Retail Investors: The New Market Force",
    description: "How millions of new investors are reshaping Indian capital markets.",
    category: "prime",
    tags: ["investing", "markets", "retail"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/prime",
    readTime: "5 min",
    contentType: "Opinion"
  },
  {
    id: "prime-12",
    title: "The Gig Economy Transformation",
    description: "Understanding the shift towards freelance work and its economic implications.",
    category: "prime",
    tags: ["gig economy", "careers", "future of work"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&q=80",
    link: "https://economictimes.indiatimes.com/prime",
    readTime: "6 min",
    contentType: "Feature"
  }
];

export const trending = [
  {
    id: "trend-1",
    title: "RBI Monetary Policy Decision Today",
    description: "Markets await crucial interest rate announcement from Reserve Bank of India.",
    category: "markets",
    tags: ["RBI", "policy", "interest rates"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets"
  },
  {
    id: "trend-2",
    title: "IPO Alert: Massive Tech Listing Next Week",
    description: "India's largest fintech company to debut on NSE with Rs 10,000 crore offering.",
    category: "markets",
    tags: ["IPO", "fintech", "stocks"],
    audience: ["Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets/ipo"
  },
  {
    id: "trend-3",
    title: "Global Markets React to Fed Decision",
    description: "US Federal Reserve signals rate trajectory, impact on emerging markets analyzed.",
    category: "markets",
    tags: ["Fed", "global", "markets"],
    audience: ["Working Professional"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets"
  },
  {
    id: "trend-4",
    title: "India GDP Growth Forecast Raised to 7.8%",
    description: "Economic growth forecast upgraded as manufacturing and services sectors show strength.",
    category: "prime",
    tags: ["GDP", "economy", "growth"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80",
    link: "https://economictimes.indiatimes.com/news/economy"
  },
  {
    id: "trend-5",
    title: "Mega Merger: Two Industry Giants in Talks",
    description: "Two leading conglomerates in advanced discussions for landmark merger deal.",
    category: "prime",
    tags: ["merger", "corporate", "deals"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1553028826-f4804a6dba3b?w=800&q=80",
    link: "https://economictimes.indiatimes.com/industry"
  },
  {
    id: "trend-6",
    title: "New Tax Rules Effective April 1st",
    description: "Key changes in income tax regulations that every taxpayer must know.",
    category: "prime",
    tags: ["tax", "policy", "finance"],
    audience: ["Student", "Working Professional", "Business Owner"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/tax"
  },
  {
    id: "trend-7",
    title: "AI Startup Raises $500M in Record Funding",
    description: "Indian AI unicorn secures largest ever Series D in the country's tech ecosystem.",
    category: "technology",
    tags: ["AI", "startup", "funding"],
    audience: ["Working Professional", "Business Owner", "Student"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups"
  },
  {
    id: "trend-8",
    title: "Sensex Breaches 90,000 Mark Intraday",
    description: "Historic milestone as Indian benchmark index touches unprecedented levels.",
    category: "markets",
    tags: ["sensex", "stocks", "milestone"],
    audience: ["Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/markets"
  }
];

export const wealth = [
  {
    id: "wealth-1",
    title: "Best Mutual Funds for 2026",
    description: "Top-performing equity and debt funds to consider for your portfolio this year.",
    category: "wealth",
    tags: ["mutual funds", "investing", "portfolio"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/invest"
  },
  {
    id: "wealth-2",
    title: "SIP vs Lumpsum: The Ultimate Guide",
    description: "Which investment strategy works better for different financial goals and risk profiles?",
    category: "wealth",
    tags: ["SIP", "investing", "strategy"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/invest"
  },
  {
    id: "wealth-3",
    title: "Retirement Planning at 30: Start Now",
    description: "Why starting early is crucial and how to build a solid retirement corpus.",
    category: "wealth",
    tags: ["retirement", "planning", "savings"],
    audience: ["Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/plan"
  },
  {
    id: "wealth-4",
    title: "Real Estate vs Stocks: Long-Term Comparison",
    description: "Detailed analysis comparing returns, risks, and liquidity of both asset classes.",
    category: "wealth",
    tags: ["real estate", "stocks", "comparison"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/invest"
  },
  {
    id: "wealth-5",
    title: "Emergency Fund: How Much Do You Need?",
    description: "Calculate your ideal emergency corpus and where to park it for liquidity.",
    category: "wealth",
    tags: ["emergency fund", "savings", "planning"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/save"
  },
  {
    id: "wealth-6",
    title: "Health Insurance: Complete Buying Guide",
    description: "Everything you need to know before purchasing health insurance for your family.",
    category: "wealth",
    tags: ["insurance", "health", "protection"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/insure"
  },
  {
    id: "wealth-7",
    title: "NPS vs PPF vs EPF: Which is Best?",
    description: "Comprehensive comparison of government-backed retirement and savings schemes.",
    category: "wealth",
    tags: ["NPS", "PPF", "retirement"],
    audience: ["Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/invest"
  },
  {
    id: "wealth-8",
    title: "Gold Investment: Physical vs Digital",
    description: "Sovereign Gold Bonds, Gold ETFs, or physical gold - making the right choice.",
    category: "wealth",
    tags: ["gold", "investment", "SGB"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1610375461246-83df859d849d?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/invest"
  },
  {
    id: "wealth-9",
    title: "Credit Score: How to Improve It",
    description: "Practical tips to boost your CIBIL score and get better loan interest rates.",
    category: "wealth",
    tags: ["credit score", "loans", "finance"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/borrow"
  },
  {
    id: "wealth-10",
    title: "Estate Planning Essentials",
    description: "Wills, nominations, and succession planning to protect your family's future.",
    category: "wealth",
    tags: ["estate", "will", "succession"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/plan"
  },
  {
    id: "wealth-11",
    title: "Child Education Planning",
    description: "Building a corpus for your child's higher education through smart investments.",
    category: "wealth",
    tags: ["education", "children", "planning"],
    audience: ["Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/plan"
  },
  {
    id: "wealth-12",
    title: "Debt Management Strategies",
    description: "How to tackle multiple loans and become debt-free systematically.",
    category: "wealth",
    tags: ["debt", "loans", "management"],
    audience: ["Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/wealth/borrow"
  }
];

export const startups = [
  {
    id: "startup-1",
    title: "Zepto's Path to Profitability",
    description: "How the quick commerce unicorn is redefining unit economics.",
    category: "startups",
    tags: ["quick commerce", "unicorn", "profitability"],
    audience: ["Working Professional", "Business Owner", "Student"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups",
    funding: "Series F",
    sector: "Quick Commerce"
  },
  {
    id: "startup-2",
    title: "D2C Brands: The New Retail Revolution",
    description: "Direct-to-consumer startups challenging traditional FMCG giants.",
    category: "startups",
    tags: ["D2C", "retail", "consumer"],
    audience: ["Business Owner", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups",
    funding: "Series B",
    sector: "Consumer"
  },
  {
    id: "startup-3",
    title: "HealthTech Startups Transforming Care",
    description: "From telemedicine to AI diagnostics - revolutionizing patient care.",
    category: "startups",
    tags: ["healthtech", "healthcare", "innovation"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups",
    funding: "Series C",
    sector: "HealthTech"
  },
  {
    id: "startup-4",
    title: "FinTech Disruption: UPI's Next Chapter",
    description: "How payment startups are building credit and wealth products.",
    category: "startups",
    tags: ["fintech", "UPI", "payments"],
    audience: ["Working Professional", "Student"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups",
    funding: "Series D",
    sector: "FinTech"
  },
  {
    id: "startup-5",
    title: "Startup Funding: Q1 2026 Report",
    description: "Detailed analysis of funding trends and investor sentiment.",
    category: "startups",
    tags: ["funding", "VC", "investment"],
    audience: ["Business Owner", "Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1553028826-f4804a6dba3b?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups",
    funding: "$2.8B Total",
    sector: "Ecosystem"
  },
  {
    id: "startup-6",
    title: "AgriTech: Farming Goes Digital",
    description: "Startups helping farmers with precision agriculture.",
    category: "startups",
    tags: ["agritech", "farming", "rural"],
    audience: ["Business Owner", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups",
    funding: "Series A",
    sector: "AgriTech"
  },
  {
    id: "startup-7",
    title: "EdTech 2.0: Beyond Online Classes",
    description: "Education startups pivoting to skill-based learning.",
    category: "startups",
    tags: ["edtech", "education", "skills"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups",
    funding: "Series B",
    sector: "EdTech"
  },
  {
    id: "startup-8",
    title: "Climate Tech: India's Green Startups",
    description: "Founders building solutions for carbon capture and clean energy.",
    category: "startups",
    tags: ["climate", "sustainability", "cleantech"],
    audience: ["Working Professional", "Business Owner", "Student"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups",
    funding: "Seed",
    sector: "CleanTech"
  },
  {
    id: "startup-9",
    title: "SaaS Startups: Global Ambitions",
    description: "Indian B2B software companies expanding internationally.",
    category: "startups",
    tags: ["SaaS", "B2B", "software"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups",
    funding: "Series E",
    sector: "SaaS"
  },
  {
    id: "startup-10",
    title: "EV Startups: The Electric Dream",
    description: "Startups electrifying Indian mobility from two-wheelers to trucks.",
    category: "startups",
    tags: ["EV", "mobility", "electric"],
    audience: ["Working Professional", "Student"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups",
    funding: "Series C",
    sector: "EV/Mobility"
  },
  {
    id: "startup-11",
    title: "Founder Stories: From Idea to IPO",
    description: "Inspiring journeys of entrepreneurs who built billion-dollar companies.",
    category: "startups",
    tags: ["founders", "entrepreneurship", "inspiration"],
    audience: ["Student", "Working Professional", "Business Owner"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups",
    funding: "IPO",
    sector: "Success Story"
  },
  {
    id: "startup-12",
    title: "Logistics Startups: Last Mile Innovation",
    description: "How delivery startups are solving India's complex logistics puzzle.",
    category: "startups",
    tags: ["logistics", "delivery", "supply chain"],
    audience: ["Business Owner", "Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/startups",
    funding: "Series D",
    sector: "Logistics"
  }
];

export const technology = [
  {
    id: "tech-1",
    title: "ChatGPT-5: What's New and What It Means",
    description: "Deep dive into the latest AI capabilities and their business impact.",
    category: "technology",
    tags: ["AI", "ChatGPT", "innovation"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/technology",
    topic: "AI",
    impact: "Enterprise Automation"
  },
  {
    id: "tech-2",
    title: "5G Revolution: India's Digital Leap",
    description: "How 5G is enabling new use cases across industries.",
    category: "technology",
    tags: ["5G", "telecom", "connectivity"],
    audience: ["Working Professional"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/technology",
    topic: "Telecom",
    impact: "Connectivity"
  },
  {
    id: "tech-3",
    title: "Cybersecurity Threats in 2026",
    description: "Emerging cyber risks and protection strategies.",
    category: "technology",
    tags: ["cybersecurity", "security", "threats"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/technology",
    topic: "Security",
    impact: "Risk Mitigation"
  },
  {
    id: "tech-4",
    title: "Cloud Computing: AWS vs Azure vs GCP",
    description: "Comprehensive comparison for enterprise adoption.",
    category: "technology",
    tags: ["cloud", "AWS", "enterprise"],
    audience: ["Working Professional"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/technology",
    topic: "Cloud",
    impact: "Infrastructure"
  },
  {
    id: "tech-5",
    title: "Blockchain Beyond Crypto",
    description: "Enterprise applications in supply chain and finance.",
    category: "technology",
    tags: ["blockchain", "enterprise", "innovation"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/technology",
    topic: "Blockchain",
    impact: "Transparency"
  },
  {
    id: "tech-6",
    title: "Quantum Computing: The Next Frontier",
    description: "Understanding quantum technology and its potential.",
    category: "technology",
    tags: ["quantum", "computing", "future"],
    audience: ["Student", "Working Professional"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/technology",
    topic: "Quantum",
    impact: "Problem Solving"
  },
  {
    id: "tech-7",
    title: "AR/VR: The Metaverse Reality Check",
    description: "Current state and realistic enterprise applications.",
    category: "technology",
    tags: ["AR", "VR", "metaverse"],
    audience: ["Working Professional", "Student"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/technology",
    topic: "AR/VR",
    impact: "User Experience"
  },
  {
    id: "tech-8",
    title: "IoT in Smart Cities",
    description: "Connected devices making urban infrastructure efficient.",
    category: "technology",
    tags: ["IoT", "smart cities", "infrastructure"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/technology",
    topic: "IoT",
    impact: "Urban Planning"
  },
  {
    id: "tech-9",
    title: "Low-Code/No-Code Platforms",
    description: "Democratizing software development for business users.",
    category: "technology",
    tags: ["low-code", "no-code", "development"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/technology",
    topic: "Development",
    impact: "Productivity"
  },
  {
    id: "tech-10",
    title: "Data Privacy: DPDP Act Explained",
    description: "India's new data protection law for businesses.",
    category: "technology",
    tags: ["privacy", "data", "regulation"],
    audience: ["Working Professional", "Business Owner"],
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/technology",
    topic: "Privacy",
    impact: "Compliance"
  },
  {
    id: "tech-11",
    title: "Edge Computing: Processing at Source",
    description: "Why moving computation closer to data is trending.",
    category: "technology",
    tags: ["edge", "computing", "infrastructure"],
    audience: ["Working Professional"],
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/technology",
    topic: "Edge",
    impact: "Latency Reduction"
  },
  {
    id: "tech-12",
    title: "Tech Jobs: Skills in Demand 2026",
    description: "Most sought-after skills and certifications.",
    category: "technology",
    tags: ["careers", "skills", "jobs"],
    audience: ["Student", "Working Professional"],
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&q=80",
    link: "https://economictimes.indiatimes.com/tech/technology",
    topic: "Careers",
    impact: "Career Growth"
  }
];

// Helper to get all items
export const getAllItems = () => {
  return [...events, ...masterclasses, ...markets, ...prime, ...trending, ...wealth, ...startups, ...technology];
};

// Helper to find item by ID
export const getItemById = (id) => {
  return getAllItems().find(item => item.id === id);
};

// Helper to get items by section type
export const getItemsBySection = (section) => {
  const sectionMap = {
    events,
    masterclasses,
    markets,
    prime,
    trending,
    wealth,
    startups,
    technology
  };
  return sectionMap[section] || [];
};
